repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: bash -c 'cd backend && uv run ruff check --fix --config pyproject.toml'
        language: system
        types_or: [python, pyi]
        pass_filenames: false

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: bash -c 'cd backend && uv run ruff format --config pyproject.toml'
        language: system
        types_or: [python, pyi]
        pass_filenames: false

  - repo: local
    hooks:
      - id: mypy
        name: mypy type check
        entry: bash -c 'cd backend && uv run mypy . --config-file pyproject.toml'
        language: system
        types: [python]
        pass_filenames: false

# Global settings
default_stages: [pre-commit]
fail_fast: false  # Run all hooks even if one fails, to see all errors at once
