name: CV Processing Service CI/CD

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
      OPENAI_API_KEY:
        required: false
  push:
    paths:
      - 'cv-processing-service/**'
      - '.github/workflows/cv-processing-service.yml'
  pull_request:
    paths:
      - 'cv-processing-service/**'
      - '.github/workflows/cv-processing-service.yml'

env:
  SERVICE_NAME: cv-processing-service
  SERVICE_PATH: ./cv-processing-service
  PYTHON_VERSION: "3.11"

jobs:
  # Service-specific tests
  test-cv-processing:
    name: Test CV Processing Service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -r ${{ env.SERVICE_PATH }}/requirements.txt

      - name: Run service-specific linting
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          ruff check . --output-format=github
          ruff format --check .

      - name: Run service-specific type checking
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          mypy . --ignore-missing-imports

      - name: Run unit tests with coverage
        env:
          LLM_API_KEY: test-key-for-testing-only-not-real
          OPENAI_API_KEY: test-key-for-testing-only-not-real
          TEST_MODE: unit
        run: |
          pytest ${{ env.SERVICE_PATH }}/tests/unit/ \
            --cov=${{ env.SERVICE_NAME }} \
            --cov-report=xml:${{ env.SERVICE_NAME }}-coverage.xml \
            --cov-report=html:${{ env.SERVICE_NAME }}-htmlcov \
            --cov-report=term-missing \
            --cov-fail-under=30 \
            --junitxml=${{ env.SERVICE_NAME }}-results.xml \
            -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./${{ env.SERVICE_NAME }}-coverage.xml
          flags: ${{ env.SERVICE_NAME }}
          name: codecov-${{ env.SERVICE_NAME }}
          fail_ci_if_error: false

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.SERVICE_NAME }}-test-results-${{ matrix.python-version }}
          path: |
            ${{ env.SERVICE_NAME }}-results.xml
            ${{ env.SERVICE_NAME }}-htmlcov/

  # Security scanning
  security-scan-cv-processing:
    name: Security Scan CV Processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          pip install -r ${{ env.SERVICE_PATH }}/requirements.txt

      - name: Run Bandit security scan
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          bandit -r . -f json -o bandit-${{ env.SERVICE_NAME }}.json
        continue-on-error: true

      - name: Run Safety vulnerability check
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          safety check --json --output safety-${{ env.SERVICE_NAME }}.json
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports-${{ env.SERVICE_NAME }}
          path: |
            ${{ env.SERVICE_PATH }}/bandit-${{ env.SERVICE_NAME }}.json
            ${{ env.SERVICE_PATH }}/safety-${{ env.SERVICE_NAME }}.json

  # Build Docker image for testing
  build-cv-processing:
    name: Build CV Processing Docker
    runs-on: ubuntu-latest
    needs: [test-cv-processing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SERVICE_PATH }}
          platforms: linux/amd64
          push: false
          tags: ${{ env.SERVICE_NAME }}:test
          cache-from: type=gha,scope=${{ env.SERVICE_NAME }}
          cache-to: type=gha,mode=max,scope=${{ env.SERVICE_NAME }}

      - name: Test Docker image
        run: |
          docker run --rm ${{ env.SERVICE_NAME }}:test python -c "import sys; print(f'Python {sys.version}')"

  # Container security scanning
  container-security-cv-processing:
    name: Container Security CV Processing
    runs-on: ubuntu-latest
    needs: [build-cv-processing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SERVICE_PATH }}
          platforms: linux/amd64
          push: false
          tags: ${{ env.SERVICE_NAME }}:scan
          cache-from: type=gha,scope=${{ env.SERVICE_NAME }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.SERVICE_NAME }}:scan
          format: 'sarif'
          output: 'trivy-${{ env.SERVICE_NAME }}.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-${{ env.SERVICE_NAME }}.sarif'

  # Service-specific integration tests
  integration-test-cv-processing:
    name: Integration Test CV Processing
    runs-on: ubuntu-latest
    needs: [build-cv-processing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run service integration tests
        env:
          LLM_API_KEY: test-key-for-testing-only-not-real
          OPENAI_API_KEY: test-key-for-testing-only-not-real
          TEST_MODE: integration
        run: |
          pytest tests/integration/test_${{ env.SERVICE_NAME }}_integration.py \
            --cov=${{ env.SERVICE_NAME }} \
            --cov-report=xml:${{ env.SERVICE_NAME }}-integration-coverage.xml \
            --junitxml=${{ env.SERVICE_NAME }}-integration-results.xml \
            -v

      - name: Upload integration coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./${{ env.SERVICE_NAME }}-integration-coverage.xml
          flags: integration-${{ env.SERVICE_NAME }}
          name: codecov-integration-${{ env.SERVICE_NAME }}

  # AI/LLM specific tests
  ai-model-tests:
    name: AI Model Tests
    runs-on: ubuntu-latest
    needs: [test-cv-processing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -r ${{ env.SERVICE_PATH }}/requirements.txt

      - name: Test LLM integration (mocked)
        env:
          LLM_API_KEY: test-key-for-testing-only-not-real
          TEST_MODE: ai_model
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          pytest tests/unit/test_llm_service.py \
            tests/unit/test_processing_service.py \
            -v --tb=short

      - name: Test embedding model functionality
        env:
          TEST_MODE: embedding
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          pytest tests/unit/test_content_structure_service.py \
            tests/unit/test_embedding_service.py \
            -v --tb=short