name: Mypy Type Checks

on:
  push:
    branches: [ main, v2 ]
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: |
          cd backend
          uv venv

      - name: Install dependencies
        run: |
          cd backend
          # Use uv sync to install all dependencies including dev group
          uv sync --all-groups

      - name: Run mypy on backend
        run: |
          cd backend
          source .venv/bin/activate
          mypy . --config-file pyproject.toml
