name: Mypy Type Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run mypy Checks on Microservices
        run: |
          mypy --ignore-missing-imports ./cv-intake-service
          mypy --ignore-missing-imports ./cv-processing-service
          mypy --ignore-missing-imports ./cv-search-service
          mypy --ignore-missing-imports ./cv-storage-service
