name: Ruff Linting

on:
  push:
    branches: [ main, v2 ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install ruff
        run: |
          uv pip install --system ruff

      - name: Run Ruff format check
        run: |
          cd backend
          ruff format --check .

      - name: Run Ruff linting
        run: |
          cd backend
          ruff check .
