name: tests

on:
  push:
    branches: [ main, v2 ]
  pull_request:
    branches: [ main ]

env:
  TEXT_LLM_API_KEY: ${{ secrets.TEXT_LLM_API_KEY }}
  OCR_LLM_API_KEY: ${{ secrets.OCR_LLM_API_KEY }}
  GITHUB_ACTIONS: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create .env file from example
      run: |
        cp backend/.env.example backend/.env
        sed -i "s|TEXT_LLM_API_KEY=.*|TEXT_LLM_API_KEY=$TEXT_LLM_API_KEY|" backend/.env
        sed -i "s|OCR_LLM_API_KEY=.*|OCR_LLM_API_KEY=$OCR_LLM_API_KEY|" backend/.env
        echo "✓ Created .env file with API keys from secrets"

    - name: Start all services
      run: docker compose up -d --wait

    - name: Run tests
      run: docker compose exec -T backend .venv/bin/python manage.py test --verbosity=2

    - name: Stop services
      if: always()
      run: |
        docker compose down -v